### ISSUE TITLE
Error initializing Vagrant Image

### ISSUE THREAD

**Issue by arnonuem** [dhamaniasad/crestify#27]
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

```
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/opt/crestify/fabfile.py", line 18, in vagrant_init
    execute(install_python_reqs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/opt/crestify/fabfile.py", line 31, in install_python_reqs
    sudo('apt-get update --fix-missing')
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 687, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 1148, in sudo
    capture_buffer_size=capture_buffer_size,
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 930, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/lib/python2.7/dist-packages/fabric/state.py", line 424, in default_channel
    chan = _open_session()
  File "/usr/local/lib/python2.7/dist-packages/fabric/state.py", line 416, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 481, in connect
    client.connect(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 338, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 500, in start_client
    raise e
AttributeError: _init_cffi_1_0_external_module
```

Any ideas?

**Comment by dhamaniasad** [comment]
Can you try installing `libffi-dev` & `libssl-dev` and report back?

**Comment by arnonuem** [comment]
I have these libs already installed.

**Comment by arnonuem** [comment]
Do you have any other ideas what i can do about this.

**Comment by dhamaniasad** [comment]
Closing as we will no longer be using Vagrant going forward.
